language: csharp
solution: .\StarterProject\StarterProject.sln

dist: trusty
sudo: required
mono: none
dotnet: 1.0.0-preview2-003131

script:
  - dotnet restore
  - pushd StarterProject/src/StarterProject.Web.Api && dotnet pack -c Release && popd
  - pushd StarterProject/src/StarterProject.Web.Api.UnitTests && dotnet test && popd
  - pushd StarterProject/src/StarterProject.Web.Api.IntegrationTests && dotnet test && popd